In [119]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import ast
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import joblib

In [120]:
credits = pd.read_csv("tmdb_5000_credits.csv")

In [121]:
movies = pd.read_csv("tmdb_5000_movies.csv")

In [122]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [123]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [124]:
movies.shape

(4803, 20)

In [125]:
credits.shape

(4803, 4)

In [126]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [127]:
credits.columns

Index(['movie_id', 'title', 'cast', 'crew'], dtype='object')

In [128]:
movies_merged = movies.merge(credits,
                             left_on = "id",
                             right_on = "movie_id"
                            )

In [129]:
movies_merged.shape

(4803, 24)

In [130]:
movies_merged.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title_x', 'vote_average',
       'vote_count', 'movie_id', 'title_y', 'cast', 'crew'],
      dtype='object')

In [131]:
movies_merged.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title_x,vote_average,vote_count,movie_id,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [132]:
movies_merged.dtypes

budget                    int64
genres                   object
homepage                 object
id                        int64
keywords                 object
original_language        object
original_title           object
overview                 object
popularity              float64
production_companies     object
production_countries     object
release_date             object
revenue                   int64
runtime                 float64
spoken_languages         object
status                   object
tagline                  object
title_x                  object
vote_average            float64
vote_count                int64
movie_id                  int64
title_y                  object
cast                     object
crew                     object
dtype: object

In [133]:
movies_merged.describe

<bound method NDFrame.describe of          budget                                             genres  \
0     237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1     300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2     245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3     250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4     260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
...         ...                                                ...
4798     220000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4799       9000  [{"id": 35, "name": "Comedy"}, {"id": 10749, "...
4800          0  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...
4801          0                                                 []
4802          0                [{"id": 99, "name": "Documentary"}]

                                               homepage      id  \
0                           http://www.avatarmovie.com/   19995
1          http://disney.go.com/disneypictures/pirates/     285
2           http://www.sonypictures.com/movies/spectre/  206647
3                    http://www.thedarkknightrises.com/   49026
4                  http://movies.disney.com/john-carter   49529
...                                                 ...     ...
4798                                                NaN    9367
4799                                                NaN   72766
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617
4801                        http://shanghaicalling.com/  126186
4802                                                NaN   25975

                                               keywords original_language  \
0     [{"id": 1463, "name": "culture clash"}, {"id":...                en
1     [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en
2     [{"id": 470, "name": "spy"}, {"id": 818, "name...                en
3     [{"id": 849, "name": "dc comics"}, {"id": 853,...                en
4     [{"id": 818, "name": "based on novel"}, {"id":...                en
...                                                 ...               ...
4798  [{"id": 5616, "name": "united states\u2013mexi...                es
4799                                                 []                en
4800  [{"id": 248, "name": "date"}, {"id": 699, "nam...                en
4801                                                 []                en
4802  [{"id": 1523, "name": "obsession"}, {"id": 224...                en

                                original_title  \
0                                       Avatar
1     Pirates of the Caribbean: At World's End
2                                      Spectre
3                        The Dark Knight Rises
4                                  John Carter
...                                        ...
4798                               El Mariachi
4799                                 Newlyweds
4800                 Signed, Sealed, Delivered
4801                          Shanghai Calling
4802                         My Date with Drew

                                               overview  popularity  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577
1     Captain Barbossa, long believed to be dead, ha...  139.082615
2     A cryptic message from Bond’s past sends him o...  107.376788
3     Following the death of District Attorney Harve...  112.312950
4     John Carter is a war-weary, former military ca...   43.926995
...                                                 ...         ...
4798  El Mariachi just wants to play his guitar and ...   14.269792
4799  A newlywed couple's honeymoon is upended by th...    0.642552
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476
4801  When ambitious New York attorney Sam is sent t...    0.857008
4802  Ever since the second grade when he first saw ...    1.929883

                                   production_companies  ...  \
0     [{"name": "Ingenious Film Partners", "id": 289...  ...
1     [{"name": "Walt Disney Pictures", "id": 2}, {"...  ...
2     [{"name": "Columbia Pictures", "id": 5}, {"nam...  ...
3     [{"name": "Legendary Pictures", "id": 923}, {"...  ...
4           [{"name": "Walt Disney Pictures", "id": 2}]  ...
...                                                 ...  ...
4798           [{"name": "Columbia Pictures", "id": 5}]  ...
4799                                                 []  ...
4800  [{"name": "Front Street Pictures", "id": 3958}...  ...
4801                                                 []  ...
4802  [{"name": "rusty bear entertainment", "id": 87...  ...

                                       spoken_languages    status  \
0     [{"iso_639_1": "en", "name": "English"}, {"iso...  Released
1              [{"iso_639_1": "en", "name": "English"}]  Released
2     [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released
3              [{"iso_639_1": "en", "name": "English"}]  Released
4              [{"iso_639_1": "en", "name": "English"}]  Released
...                                                 ...       ...
4798      [{"iso_639_1": "es", "name": "Espa\u00f1ol"}]  Released
4799                                                 []  Released
4800           [{"iso_639_1": "en", "name": "English"}]  Released
4801           [{"iso_639_1": "en", "name": "English"}]  Released
4802           [{"iso_639_1": "en", "name": "English"}]  Released

                                                tagline  \
0                           Enter the World of Pandora.
1        At the end of the world, the adventure begins.
2                                 A Plan No One Escapes
3                                       The Legend Ends
4                  Lost in our world, found in another.
...                                                 ...
4798  He didn't come looking for trouble, but troubl...
4799  A newlywed couple's honeymoon is upended by th...
4800                                                NaN
4801                           A New Yorker in Shanghai
4802                                                NaN

                                       title_x vote_average vote_count  \
0                                       Avatar          7.2      11800
1     Pirates of the Caribbean: At World's End          6.9       4500
2                                      Spectre          6.3       4466
3                        The Dark Knight Rises          7.6       9106
4                                  John Carter          6.1       2124
...                                        ...          ...        ...
4798                               El Mariachi          6.6        238
4799                                 Newlyweds          5.9          5
4800                 Signed, Sealed, Delivered          7.0          6
4801                          Shanghai Calling          5.7          7
4802                         My Date with Drew          6.3         16

     movie_id                                   title_y  \
0       19995                                    Avatar
1         285  Pirates of the Caribbean: At World's End
2      206647                                   Spectre
3       49026                     The Dark Knight Rises
4       49529                               John Carter
...       ...                                       ...
4798     9367                               El Mariachi
4799    72766                                 Newlyweds
4800   231617                 Signed, Sealed, Delivered
4801   126186                          Shanghai Calling
4802    25975                         My Date with Drew

                                                   cast  \
0     [{"cast_id": 242, "character": "Jake Sully", "...
1     [{"cast_id": 4, "character": "Captain Jack Spa...
2     [{"cast_id": 1, "character": "James Bond", "cr...
3     [{"cast_id": 2, "character": "Bruce Wayne / Ba...
4     [{"cast_id": 5, "character": "John Carter", "c...
...                                                 ...
4798  [{"cast_id": 1, "character": "El Mariachi", "c...
4799  [{"cast_id": 1, "character": "Buzzy", "credit_...
4800  [{"cast_id": 8, "character": "Oliver O\u2019To...
4801  [{"cast_id": 3, "character": "Sam", "credit_id...
4802  [{"cast_id": 3, "character": "Herself", "credi...

                                                   crew
0     [{"credit_id": "52fe48009251416c750aca23", "de...
1     [{"credit_id": "52fe4232c3a36847f800b579", "de...
2     [{"credit_id": "54805967c3a36829b5002c41", "de...
3     [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
...                                                 ...
4798  [{"credit_id": "52fe44eec3a36847f80b280b", "de...
4799  [{"credit_id": "52fe487dc3a368484e0fb013", "de...
4800  [{"credit_id": "52fe4df3c3a36847f8275ecf", "de...
4801  [{"credit_id": "52fe4ad9c3a368484e16a36b", "de...
4802  [{"credit_id": "58ce021b9251415a390165d9", "de...

[4803 rows x 24 columns]>

In [134]:
movies_merged.isna()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title_x,vote_average,vote_count,movie_id,title_y,cast,crew
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4799,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4800,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
4801,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4802,False,False,True,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False

In [135]:
movies_merged.isna().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title_x                    0
vote_average               0
vote_count                 0
movie_id                   0
title_y                    0
cast                       0
crew                       0
dtype: int64

In [136]:
# 8. If Movie Id and Id are the same
(movies_merged["id"] == movies_merged["movie_id"]).all()

np.True_

In [137]:
# 9. Drop Movie Id 
movies_merged = movies_merged.drop("movie_id",axis=1)

In [138]:
# 10. Data Overview
movies_merged.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title_x', 'vote_average',
       'vote_count', 'title_y', 'cast', 'crew'],
      dtype='object')

In [139]:
movies_merged.shape

(4803, 23)

In [140]:
# Ckeck for Duplicated Rows
movies_merged.duplicated().sum()

np.int64(0)

In [141]:
movies_merged.isna().sum(axis=0)

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title_x                    0
vote_average               0
vote_count                 0
title_y                    0
cast                       0
crew                       0
dtype: int64

In [142]:
# .13 Drop 2 Columns
movies_merged = movies_merged.drop(["homepage", "tagline"], axis=1)

In [143]:
# .14 Drop 2 Rows
movies_merged = movies_merged.dropna(subset=["overview", "runtime"])

In [144]:
# .15 Summary
movies_merged.isna().sum()

budget                  0
genres                  0
id                      0
keywords                0
original_language       0
original_title          0
overview                0
popularity              0
production_companies    0
production_countries    0
release_date            1
revenue                 0
runtime                 0
spoken_languages        0
status                  0
title_x                 0
vote_average            0
vote_count              0
title_y                 0
cast                    0
crew                    0
dtype: int64

In [145]:
# .16 Checking Indivual Column 
movies_merged[movies_merged["release_date"].isna()]

,budget,genres,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,...,revenue,runtime,spoken_languages,status,title_x,vote_average,vote_count,title_y,cast,crew
4553,0,[],380097,[],en,America Is Still the Place,1971 post civil rights San Francisco seemed li...,0.0,[],[],...,0,0.0,[],Released,America Is Still the Place,0.0,0,America Is Still the Place,[],[]

In [146]:
movies_merged = movies_merged.dropna(subset=["release_date"])

In [147]:
# .18 Summary
movies_merged.isna().sum()

budget                  0
genres                  0
id                      0
keywords                0
original_language       0
original_title          0
overview                0
popularity              0
production_companies    0
production_countries    0
release_date            0
revenue                 0
runtime                 0
spoken_languages        0
status                  0
title_x                 0
vote_average            0
vote_count              0
title_y                 0
cast                    0
crew                    0
dtype: int64

In [148]:
# .19 Checking Data Types
movies_merged.dtypes

budget                    int64
genres                   object
id                        int64
keywords                 object
original_language        object
original_title           object
overview                 object
popularity              float64
production_companies     object
production_countries     object
release_date             object
revenue                   int64
runtime                 float64
spoken_languages         object
status                   object
title_x                  object
vote_average            float64
vote_count                int64
title_y                  object
cast                     object
crew                     object
dtype: object

In [149]:
# .20 Convert
movies_merged["release_date"] = pd.to_datetime(movies_merged["release_date"])

In [150]:
movies_merged.dtypes

budget                           int64
genres                          object
id                               int64
keywords                        object
original_language               object
original_title                  object
overview                        object
popularity                     float64
production_companies            object
production_countries            object
release_date            datetime64[ns]
revenue                          int64
runtime                        float64
spoken_languages                object
status                          object
title_x                         object
vote_average                   float64
vote_count                       int64
title_y                         object
cast                            object
crew                            object
dtype: object

In [151]:
# .22 Create New Column
movies_merged["release_year"] = movies_merged["release_date"].dt.year

In [152]:
# .23 Checking The Corrections
movies_merged[["release_date", "release_year"]].head()

  release_date  release_year
0   2009-12-10          2009
1   2007-05-19          2007
2   2015-10-26          2015
3   2012-07-16          2012
4   2012-03-07          2012

In [153]:
# .24 Creating and conversion of A New Column
movies_merged["is_successful"] = (movies_merged["revenue"] > movies_merged["budget"]).astype(int)

In [154]:
# .25 Overview
movies_merged[['budget', 'revenue', 'is_successful']].head()

      budget     revenue  is_successful
0  237000000  2787965087              1
1  300000000   961000000              1
2  245000000   880674609              1
3  250000000  1084939099              1
4  260000000   284139100              1

In [155]:
# .26 Define X and y
X = movies_merged[["budget", "runtime"]]
y = movies_merged["is_successful"]

In [156]:

X_train, X_test,y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [157]:
# Create The Model
clf_model = RandomForestClassifier()

# Training
clf_model.fit(X_train,y_train)

RandomForestClassifier()

In [158]:
# Prediction
y_pred = clf_model.predict(X_test)

In [159]:
score = accuracy_score(y_test, y_pred)
print(score)

0.6614583333333334

In [160]:


# Convertion Of Text
def extract_genres(text):
    # Converting String Into list
    actual_list = ast.literal_eval(text)
    
    # Keeping only The Name from Every Element
    names_only = [item['name'] for item in actual_list]
    
    # It Joins them in a text Separated with Commas
    return ", ".join(names_only)

# 2. Application In The Function with.apply()
movies_merged["genres"] = movies_merged["genres"].apply(extract_genres)

In [161]:
# Dataset Overview
movies_merged["genres"].head()

0    Action, Adventure, Fantasy, Science Fiction
1                     Adventure, Fantasy, Action
2                       Action, Adventure, Crime
3                 Action, Crime, Drama, Thriller
4             Action, Adventure, Science Fiction
Name: genres, dtype: object

In [162]:
# Conversion to 0,1
movies_encoded = pd.get_dummies(movies_merged, columns=["genres"], dtype=int)

In [163]:
# Data Overview
movies_encoded.shape

(4799, 1197)

In [164]:
movies_encoded.columns

Index(['budget', 'id', 'keywords', 'original_language', 'original_title',
       'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date',
       ...
       'genres_War, Western', 'genres_Western',
       'genres_Western, Action, Drama, History', 'genres_Western, Adventure',
       'genres_Western, Animation, Adventure, Comedy, Family',
       'genres_Western, Comedy', 'genres_Western, Drama',
       'genres_Western, Drama, Adventure, Thriller', 'genres_Western, History',
       'genres_Western, History, War'],
      dtype='object', length=1197)

In [165]:
# Clearly Seperation 
genres_encoded = movies_merged["genres"].str.get_dummies(sep=", ")

# We Connect Them to Our Original dataset
movies_final = pd.concat([movies_merged, genres_encoded], axis=1)

In [166]:
# Dataset Overview
movies_final.shape

(4799, 43)

In [167]:
# 42. Dataset Overview
movies_final.columns

Index(['budget', 'genres', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'title_x', 'vote_average', 'vote_count',
       'title_y', 'cast', 'crew', 'release_year', 'is_successful', 'Action',
       'Adventure', 'Animation', 'Comedy', 'Crime', 'Documentary', 'Drama',
       'Family', 'Fantasy', 'Foreign', 'History', 'Horror', 'Music', 'Mystery',
       'Romance', 'Science Fiction', 'TV Movie', 'Thriller', 'War', 'Western'],
      dtype='object')

In [168]:
# .43 Implementing Basic Features
basic_features = ["budget","runtime","release_year"]

# .44 Characteristics That Are Created From Genres
genres_features = genres_encoded.columns.tolist()

# .45 Combining The Two Lists
all_features = basic_features + genres_features

In [169]:
# 46 Setting Up X and y
X = movies_final[all_features]
y = movies_final["is_successful"]

In [170]:
# .47 Checking Shapes Of X
X.shape

(4799, 23)

In [171]:
# .48 Checking Shapes Of y
y.shape

(4799,)

In [172]:
# .49 Ckecking X 
X.head

<bound method NDFrame.head of          budget  runtime  release_year  Action  Adventure  Animation  Comedy  \
0     237000000    162.0          2009       1          1          0       0
1     300000000    169.0          2007       1          1          0       0
2     245000000    148.0          2015       1          1          0       0
3     250000000    165.0          2012       1          0          0       0
4     260000000    132.0          2012       1          1          0       0
...         ...      ...           ...     ...        ...        ...     ...
4798     220000     81.0          1992       1          0          0       0
4799       9000     85.0          2011       0          0          0       1
4800          0    120.0          2013       0          0          0       1
4801          0     98.0          2012       0          0          0       0
4802          0     90.0          2005       0          0          0       0

      Crime  Documentary  Drama  ...  History  Horror  Music  Mystery  \
0         0            0      0  ...        0       0      0        0
1         0            0      0  ...        0       0      0        0
2         1            0      0  ...        0       0      0        0
3         1            0      1  ...        0       0      0        0
4         0            0      0  ...        0       0      0        0
...     ...          ...    ...  ...      ...     ...    ...      ...
4798      1            0      0  ...        0       0      0        0
4799      0            0      0  ...        0       0      0        0
4800      0            0      1  ...        0       0      0        0
4801      0            0      0  ...        0       0      0        0
4802      0            1      0  ...        0       0      0        0

      Romance  Science Fiction  TV Movie  Thriller  War  Western
0           0                1         0         0    0        0
1           0                0         0         0    0        0
2           0                0         0         0    0        0
3           0                0         0         1    0        0
4           0                1         0         0    0        0
...       ...              ...       ...       ...  ...      ...
4798        0                0         0         1    0        0
4799        1                0         0         0    0        0
4800        1                0         1         0    0        0
4801        0                0         0         0    0        0
4802        0                0         0         0    0        0

[4799 rows x 23 columns]>

In [173]:
# .50 Checjing X
X.columns

Index(['budget', 'runtime', 'release_year', 'Action', 'Adventure', 'Animation',
       'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy',
       'Foreign', 'History', 'Horror', 'Music', 'Mystery', 'Romance',
       'Science Fiction', 'TV Movie', 'Thriller', 'War', 'Western'],
      dtype='object')

In [174]:
# .51 Checking X Shape
X.shape

(4799, 23)

In [175]:
# .52 Length Of Genres Feature
len(genres_features)

20

In [176]:
# .53 Train_test_split The New Features
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [177]:
# .54 Quick Check Of all X and y
X_train.shape

(3839, 23)

In [178]:
X_test.shape

(960, 23)

In [179]:
y_train.shape

(3839,)

In [180]:
y_test.shape

(960,)

In [181]:
# .55 Create The Model 
clf_model_v2 = RandomForestClassifier()

In [182]:
# .56 Training
clf_model_v2.fit(X_train,y_train)

RandomForestClassifier()

In [183]:
# .57 Prediction
y_pred_new = clf_model_v2.predict(X_test)

In [184]:
# .58 Score
new_score = accuracy_score(y_test,y_pred_new)
print(new_score)

0.709375

In [185]:
# .59 Checking Why It Makes This Predictions
y.value_counts()

is_successful
1    2585
0    2214
Name: count, dtype: int64

In [186]:
# .60 Classification Report
classification_report(y_test,y_pred_new)

'              precision    recall  f1-score   support\n\n           0       0.70      0.62      0.66       431\n           1       0.72      0.78      0.75       529\n\n    accuracy                           0.71       960\n   macro avg       0.71      0.70      0.70       960\nweighted avg       0.71      0.71      0.71       960\n'

In [187]:
# .61 See Classification Report More Clearly
print(classification_report(y_test,y_pred_new))

              precision    recall  f1-score   support

           0       0.70      0.62      0.66       431
           1       0.72      0.78      0.75       529

    accuracy                           0.71       960
   macro avg       0.71      0.70      0.70       960
weighted avg       0.71      0.71      0.71       960

In [188]:
# .62 Create Confusion Matrix
cm = confusion_matrix(y_test,y_pred_new)

In [189]:
# .63 See Confusion Matrix 
cm

array([[267, 164],
       [115, 414]])

In [190]:
# .64 A Number For Every Feature
clf_model_v2.feature_importances_

array([0.33402787, 0.22572484, 0.19482428, 0.01993216, 0.01561694,
       0.00731922, 0.02127396, 0.01886147, 0.00485786, 0.02156212,
       0.01160477, 0.01224009, 0.0035148 , 0.00743198, 0.0122957 ,
       0.00893829, 0.01192984, 0.02122436, 0.01470449, 0.0006214 ,
       0.01896436, 0.00630408, 0.00622513])

In [191]:
# .65 Connecting With Our Columns all_feature
feature_importance = pd.DataFrame({
    "feature": all_features,
    "importance":
    clf_model_v2.feature_importances_
})

In [192]:
feature_importance.sort_values(
    by = "importance",
    ascending = False
)

            feature  importance
0            budget    0.334028
1           runtime    0.225725
2      release_year    0.194824
9             Drama    0.021562
6            Comedy    0.021274
17          Romance    0.021224
3            Action    0.019932
20         Thriller    0.018964
7             Crime    0.018861
4         Adventure    0.015617
18  Science Fiction    0.014704
14           Horror    0.012296
11          Fantasy    0.012240
16          Mystery    0.011930
10           Family    0.011605
15            Music    0.008938
13          History    0.007432
5         Animation    0.007319
21              War    0.006304
22          Western    0.006225
8       Documentary    0.004858
12          Foreign    0.003515
19         TV Movie    0.000621

In [193]:
# .66 Quick Ckeck Of feature_importance
feature_importance.head(10)

        feature  importance
0        budget    0.334028
1       runtime    0.225725
2  release_year    0.194824
3        Action    0.019932
4     Adventure    0.015617
5     Animation    0.007319
6        Comedy    0.021274
7         Crime    0.018861
8   Documentary    0.004858
9         Drama    0.021562

In [194]:
# .67 Ckecking The Genres Meaning Categories
feature_importance[feature_importance["feature"].isin(genres_features)]

            feature  importance
3            Action    0.019932
4         Adventure    0.015617
5         Animation    0.007319
6            Comedy    0.021274
7             Crime    0.018861
8       Documentary    0.004858
9             Drama    0.021562
10           Family    0.011605
11          Fantasy    0.012240
12          Foreign    0.003515
13          History    0.007432
14           Horror    0.012296
15            Music    0.008938
16          Mystery    0.011930
17          Romance    0.021224
18  Science Fiction    0.014704
19         TV Movie    0.000621
20         Thriller    0.018964
21              War    0.006304
22          Western    0.006225

In [195]:
# .68 Save Model

# Save Model In File 
joblib.dump(clf_model_v2, "movie_profit_predictor.pkl")

# Load Model (To A Difeerent, Empty Script)
loaded_model = joblib.load("movie_profit_predictor.pkl")

In [196]:

# Mini Deployment

# .69 We Create A Line Full Of 0 Using The Same Columns Of Train Set
new_data = pd.DataFrame(0, index=[0], columns=X_train.columns)

# .70 Filling The Exactly Values For The Information Of The New Movie
new_data["budget"] = 80_000_000
new_data["runtime"] = 125
new_data["release_year"] = 2026
new_data["Action"] = 1

# 3. Prediction From The Ready Model
prediction = loaded_model.predict(new_data)

In [197]:
# Print Prediction
print(prediction)

[1]