In [5]:
import pandas as pd
path= 'usa_hours.csv'
usa_hours = pd.read_csv(path)
df.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,REF_AREA,Reference area,MEASURE,Measure,UNIT_MEASURE,Unit of measure,...,TIME_PERIOD,Time period,OBS_VALUE,Observation value,OBS_STATUS,Observation status,UNIT_MULT,Unit multiplier,DECIMALS,Decimals
0,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,USA,United States,HW,Hours worked,H_Y_PS,Hours per year per person,...,2020,NaN,1799.777,NaN,A,Normal value,NaN,NaN,0,Zero
1,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,USA,United States,HW,Hours worked,H_Y_PS,Hours per year per person,...,2019,NaN,1822.579,NaN,A,Normal value,NaN,NaN,0,Zero
2,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,USA,United States,HW,Hours worked,H_Y_PS,Hours per year per person,...,2018,NaN,1825.660,NaN,A,Normal value,NaN,NaN,0,Zero
3,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,USA,United States,HW,Hours worked,H_Y_PS,Hours per year per person,...,2017,NaN,1820.449,NaN,A,Normal value,NaN,NaN,0,Zero
4,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,USA,United States,HW,Hours worked,H_Y_PS,Hours per year per person,...,2016,NaN,1822.366,NaN,A,Normal value,NaN,NaN,0,Zero

In [6]:
usa_hours.shape

(15, 40)

In [7]:
usa_hours.isna().sum()

STRUCTURE                    0
STRUCTURE_ID                 0
STRUCTURE_NAME               0
ACTION                       0
REF_AREA                     0
Reference area               0
MEASURE                      0
Measure                      0
UNIT_MEASURE                 0
Unit of measure              0
SEX                          0
Sex                          0
AGE                          0
Age                          0
LABOUR_FORCE_STATUS          0
Labour force status          0
WORK_PERIOD                  0
Work period                  0
HOURS_TYPE                   0
Hours type                   0
WORKER_STATUS                0
Worker status                0
WORK_TIME_ARNGMNT            0
Working time arrangement     0
AGGREGATION_OPERATION        0
Aggregation operation        0
HOUR_BANDS                   0
Hour bands                   0
JOB_COVERAGE                 0
Job coverage                 0
TIME_PERIOD                  0
Time period                 15
OBS_VALUE                    0
Observation value           15
OBS_STATUS                   0
Observation status           0
UNIT_MULT                   15
Unit multiplier             15
DECIMALS                     0
Decimals                     0
dtype: int64

In [8]:
usa_hours.dropna(axis=1, inplace=True)

In [13]:
import pandas as pd
path= 'mexico_hours.csv'
mexico_hours = pd.read_csv(path)
mexico_hours.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,REF_AREA,Reference area,MEASURE,Measure,UNIT_MEASURE,Unit of measure,...,TIME_PERIOD,Time period,OBS_VALUE,Observation value,OBS_STATUS,Observation status,UNIT_MULT,Unit multiplier,DECIMALS,Decimals
0,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,MEX,Mexico,HW,Hours worked,H_Y_PS,Hours per year per person,...,2020,NaN,2207.426,NaN,A,Normal value,NaN,NaN,0,Zero
1,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,MEX,Mexico,HW,Hours worked,H_Y_PS,Hours per year per person,...,2019,NaN,2227.517,NaN,A,Normal value,NaN,NaN,0,Zero
2,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,MEX,Mexico,HW,Hours worked,H_Y_PS,Hours per year per person,...,2018,NaN,2237.945,NaN,A,Normal value,NaN,NaN,0,Zero
3,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,MEX,Mexico,HW,Hours worked,H_Y_PS,Hours per year per person,...,2017,NaN,2237.741,NaN,A,Normal value,NaN,NaN,0,Zero
4,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,MEX,Mexico,HW,Hours worked,H_Y_PS,Hours per year per person,...,2016,NaN,2237.939,NaN,A,Normal value,NaN,NaN,0,Zero

In [14]:
mexico_hours.shape

(15, 40)

In [15]:
mexico_hours.isna().sum()

STRUCTURE                    0
STRUCTURE_ID                 0
STRUCTURE_NAME               0
ACTION                       0
REF_AREA                     0
Reference area               0
MEASURE                      0
Measure                      0
UNIT_MEASURE                 0
Unit of measure              0
SEX                          0
Sex                          0
AGE                          0
Age                          0
LABOUR_FORCE_STATUS          0
Labour force status          0
WORK_PERIOD                  0
Work period                  0
HOURS_TYPE                   0
Hours type                   0
WORKER_STATUS                0
Worker status                0
WORK_TIME_ARNGMNT            0
Working time arrangement     0
AGGREGATION_OPERATION        0
Aggregation operation        0
HOUR_BANDS                   0
Hour bands                   0
JOB_COVERAGE                 0
Job coverage                 0
TIME_PERIOD                  0
Time period                 15
OBS_VALUE                    0
Observation value           15
OBS_STATUS                   0
Observation status           0
UNIT_MULT                   15
Unit multiplier             15
DECIMALS                     0
Decimals                     0
dtype: int64

In [16]:
mexico_hours.dropna(axis=1, inplace=True)

In [29]:


# Load the CSVs
usa_hours = pd.read_csv("usa_hours.csv")
mexico_hours = pd.read_csv("mexico_hours.csv")

# Add a 'country' column to each
usa_hours['country'] = 'USA'
mexico_hours['country'] = 'Mexico'

# Concatenate the datasets
combined = pd.concat([usa_hours, mexico_hours], axis=0).reset_index(drop=True)

In [31]:


# Show all rows and columns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

combined  # this will display the full dataset including USA and Mexico

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,REF_AREA,Reference area,MEASURE,Measure,UNIT_MEASURE,Unit of measure,SEX,Sex,AGE,Age,LABOUR_FORCE_STATUS,Labour force status,WORK_PERIOD,Work period,HOURS_TYPE,Hours type,WORKER_STATUS,Worker status,WORK_TIME_ARNGMNT,Working time arrangement,AGGREGATION_OPERATION,Aggregation operation,HOUR_BANDS,Hour bands,JOB_COVERAGE,Job coverage,TIME_PERIOD,Time period,OBS_VALUE,Observation value,OBS_STATUS,Observation status,UNIT_MULT,Unit multiplier,DECIMALS,Decimals,country
0,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,USA,United States,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2020,NaN,1799.777,NaN,A,Normal value,NaN,NaN,0,Zero,USA
1,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,USA,United States,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2019,NaN,1822.579,NaN,A,Normal value,NaN,NaN,0,Zero,USA
2,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,USA,United States,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2018,NaN,1825.660,NaN,A,Normal value,NaN,NaN,0,Zero,USA
3,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,USA,United States,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2017,NaN,1820.449,NaN,A,Normal value,NaN,NaN,0,Zero,USA
4,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,USA,United States,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2016,NaN,1822.366,NaN,A,Normal value,NaN,NaN,0,Zero,USA
5,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,USA,United States,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2015,NaN,1831.118,NaN,A,Normal value,NaN,NaN,0,Zero,USA
6,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,USA,United States,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2014,NaN,1830.360,NaN,A,Normal value,NaN,NaN,0,Zero,USA
7,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,USA,United States,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2013,NaN,1825.439,NaN,A,Normal value,NaN,NaN,0,Zero,USA
8,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,USA,United States,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2012,NaN,1827.068,NaN,A,Normal value,NaN,NaN,0,Zero,USA
9,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,USA,United States,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2011,NaN,1820.304,NaN,A,Normal value,NaN,NaN,0,Zero,USA
10,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,USA,United States,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2010,NaN,1810.388,NaN,A,Normal value,NaN,NaN,0,Zero,USA
11,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,USA,United States,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2024,NaN,1795.906,NaN,A,Normal value,NaN,NaN,0,Zero,USA
12,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,USA,United States,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2023,NaN,1804.950,NaN,A,Normal value,NaN,NaN,0,Zero,USA
13,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,USA,United States,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2022,NaN,1810.944,NaN,A,Normal value,NaN,NaN,0,Zero,USA
14,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,USA,United States,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2021,NaN,1819.895,NaN,A,Normal value,NaN,NaN,0,Zero,USA
15,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,MEX,Mexico,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2020,NaN,2207.426,NaN,A,Normal value,NaN,NaN,0,Zero,Mexico
16,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,MEX,Mexico,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2019,NaN,2227.517,NaN,A,Normal value,NaN,NaN,0,Zero,Mexico
17,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,MEX,Mexico,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2018,NaN,2237.945,NaN,A,Normal value,NaN,NaN,0,Zero,Mexico
18,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,MEX,Mexico,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2017,NaN,2237.741,NaN,A,Normal value,NaN,NaN,0,Zero,Mexico
19,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,MEX,Mexico,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2016,NaN,2237.939,NaN,A,Normal value,NaN,NaN,0,Zero,Mexico
20,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,MEX,Mexico,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2015,NaN,2233.595,NaN,A,Normal value,NaN,NaN,0,Zero,Mexico
21,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,MEX,Mexico,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2014,NaN,2229.068,NaN,A,Normal value,NaN,NaN,0,Zero,Mexico
22,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,MEX,Mexico,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2013,NaN,2230.844,NaN,A,Normal value,NaN,NaN,0,Zero,Mexico
23,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,MEX,Mexico,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2012,NaN,2226.199,NaN,A,Normal value,NaN,NaN,0,Zero,Mexico
24,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,MEX,Mexico,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2011,NaN,2236.718,NaN,A,Normal value,NaN,NaN,0,Zero,Mexico
25,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,MEX,Mexico,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2010,NaN,2243.893,NaN,A,Normal value,NaN,NaN,0,Zero,Mexico
26,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,MEX,Mexico,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2024,NaN,2193.358,NaN,A,Normal value,NaN,NaN,0,Zero,Mexico
27,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,MEX,Mexico,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2023,NaN,2206.628,NaN,A,Normal value,NaN,NaN,0,Zero,Mexico
28,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,MEX,Mexico,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2022,NaN,2226.300,NaN,A,Normal value,NaN,NaN,0,Zero,Mexico
29,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,MEX,Mexico,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2021,NaN,2216.265,NaN,A,Normal value,NaN,NaN,0,Zero,Mexico

In [33]:
combined.isnull().sum()

STRUCTURE                    0
STRUCTURE_ID                 0
STRUCTURE_NAME               0
ACTION                       0
REF_AREA                     0
Reference area               0
MEASURE                      0
Measure                      0
UNIT_MEASURE                 0
Unit of measure              0
SEX                          0
Sex                          0
AGE                          0
Age                          0
LABOUR_FORCE_STATUS          0
Labour force status          0
WORK_PERIOD                  0
Work period                  0
HOURS_TYPE                   0
Hours type                   0
WORKER_STATUS                0
Worker status                0
WORK_TIME_ARNGMNT            0
Working time arrangement     0
AGGREGATION_OPERATION        0
Aggregation operation        0
HOUR_BANDS                   0
Hour bands                   0
JOB_COVERAGE                 0
Job coverage                 0
TIME_PERIOD                  0
Time period                 30
OBS_VALUE                    0
Observation value           30
OBS_STATUS                   0
Observation status           0
UNIT_MULT                   30
Unit multiplier             30
DECIMALS                     0
Decimals                     0
country                      0
dtype: int64

In [34]:
combined = combined.dropna()  # drop rows with ANY missing value

In [35]:
combined.isnull().sum()

STRUCTURE                   0
STRUCTURE_ID                0
STRUCTURE_NAME              0
ACTION                      0
REF_AREA                    0
Reference area              0
MEASURE                     0
Measure                     0
UNIT_MEASURE                0
Unit of measure             0
SEX                         0
Sex                         0
AGE                         0
Age                         0
LABOUR_FORCE_STATUS         0
Labour force status         0
WORK_PERIOD                 0
Work period                 0
HOURS_TYPE                  0
Hours type                  0
WORKER_STATUS               0
Worker status               0
WORK_TIME_ARNGMNT           0
Working time arrangement    0
AGGREGATION_OPERATION       0
Aggregation operation       0
HOUR_BANDS                  0
Hour bands                  0
JOB_COVERAGE                0
Job coverage                0
TIME_PERIOD                 0
Time period                 0
OBS_VALUE                   0
Observation value           0
OBS_STATUS                  0
Observation status          0
UNIT_MULT                   0
Unit multiplier             0
DECIMALS                    0
Decimals                    0
country                     0
dtype: int64

In [42]:
usa_hours = pd.read_csv("usa_hours.csv")
mexico_hours = pd.read_csv("mexico_hours.csv")

In [43]:
usa_hours['country'] = 'USA'
mexico_hours['country'] = 'Mexico'

In [44]:
combined = pd.concat([usa_hours, mexico_hours], axis=0).reset_index(drop=True)

In [45]:
combined.isnull().sum()

STRUCTURE                    0
STRUCTURE_ID                 0
STRUCTURE_NAME               0
ACTION                       0
REF_AREA                     0
Reference area               0
MEASURE                      0
Measure                      0
UNIT_MEASURE                 0
Unit of measure              0
SEX                          0
Sex                          0
AGE                          0
Age                          0
LABOUR_FORCE_STATUS          0
Labour force status          0
WORK_PERIOD                  0
Work period                  0
HOURS_TYPE                   0
Hours type                   0
WORKER_STATUS                0
Worker status                0
WORK_TIME_ARNGMNT            0
Working time arrangement     0
AGGREGATION_OPERATION        0
Aggregation operation        0
HOUR_BANDS                   0
Hour bands                   0
JOB_COVERAGE                 0
Job coverage                 0
TIME_PERIOD                  0
Time period                 30
OBS_VALUE                    0
Observation value           30
OBS_STATUS                   0
Observation status           0
UNIT_MULT                   30
Unit multiplier             30
DECIMALS                     0
Decimals                     0
country                      0
dtype: int64

In [47]:
combined = pd.concat([usa_hours, mexico_hours], axis=0).reset_index(drop=True)
combined.isnull().sum()

STRUCTURE                    0
STRUCTURE_ID                 0
STRUCTURE_NAME               0
ACTION                       0
REF_AREA                     0
Reference area               0
MEASURE                      0
Measure                      0
UNIT_MEASURE                 0
Unit of measure              0
SEX                          0
Sex                          0
AGE                          0
Age                          0
LABOUR_FORCE_STATUS          0
Labour force status          0
WORK_PERIOD                  0
Work period                  0
HOURS_TYPE                   0
Hours type                   0
WORKER_STATUS                0
Worker status                0
WORK_TIME_ARNGMNT            0
Working time arrangement     0
AGGREGATION_OPERATION        0
Aggregation operation        0
HOUR_BANDS                   0
Hour bands                   0
JOB_COVERAGE                 0
Job coverage                 0
TIME_PERIOD                  0
Time period                 30
OBS_VALUE                    0
Observation value           30
OBS_STATUS                   0
Observation status           0
UNIT_MULT                   30
Unit multiplier             30
DECIMALS                     0
Decimals                     0
country                      0
dtype: int64

In [48]:
combined['Time period'] = combined['Time period'].fillna("Unknown")

In [49]:
combined = combined.dropna(subset=['Time period'])

In [50]:
combined.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,REF_AREA,Reference area,MEASURE,Measure,UNIT_MEASURE,Unit of measure,SEX,Sex,AGE,Age,LABOUR_FORCE_STATUS,Labour force status,WORK_PERIOD,Work period,HOURS_TYPE,Hours type,WORKER_STATUS,Worker status,WORK_TIME_ARNGMNT,Working time arrangement,AGGREGATION_OPERATION,Aggregation operation,HOUR_BANDS,Hour bands,JOB_COVERAGE,Job coverage,TIME_PERIOD,Time period,OBS_VALUE,Observation value,OBS_STATUS,Observation status,UNIT_MULT,Unit multiplier,DECIMALS,Decimals,country
0,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,USA,United States,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2020,Unknown,1799.777,NaN,A,Normal value,NaN,NaN,0,Zero,USA
1,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,USA,United States,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2019,Unknown,1822.579,NaN,A,Normal value,NaN,NaN,0,Zero,USA
2,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,USA,United States,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2018,Unknown,1825.660,NaN,A,Normal value,NaN,NaN,0,Zero,USA
3,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,USA,United States,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2017,Unknown,1820.449,NaN,A,Normal value,NaN,NaN,0,Zero,USA
4,DATAFLOW,OECD.ELS.SAE:DSD_HW@DF_AVG_ANN_HRS_WKD(1.0),Average annual hours actually worked per worker,I,USA,United States,HW,Hours worked,H_Y_PS,Hours per year per person,_Z,Not applicable,_Z,Not applicable,EMP,Employment,A,Annual,ACTUAL,Actual,_T,Total,_Z,Not applicable,MEAN,Mean,_Z,Not applicable,_T,Total,2016,Unknown,1822.366,NaN,A,Normal value,NaN,NaN,0,Zero,USA

In [51]:
combined.isnull().sum()

STRUCTURE                    0
STRUCTURE_ID                 0
STRUCTURE_NAME               0
ACTION                       0
REF_AREA                     0
Reference area               0
MEASURE                      0
Measure                      0
UNIT_MEASURE                 0
Unit of measure              0
SEX                          0
Sex                          0
AGE                          0
Age                          0
LABOUR_FORCE_STATUS          0
Labour force status          0
WORK_PERIOD                  0
Work period                  0
HOURS_TYPE                   0
Hours type                   0
WORKER_STATUS                0
Worker status                0
WORK_TIME_ARNGMNT            0
Working time arrangement     0
AGGREGATION_OPERATION        0
Aggregation operation        0
HOUR_BANDS                   0
Hour bands                   0
JOB_COVERAGE                 0
Job coverage                 0
TIME_PERIOD                  0
Time period                  0
OBS_VALUE                    0
Observation value           30
OBS_STATUS                   0
Observation status           0
UNIT_MULT                   30
Unit multiplier             30
DECIMALS                     0
Decimals                     0
country                      0
dtype: int64

In [54]:
combined['UNIT_MULT'] = combined['UNIT_MULT'].fillna(combined['Unit multiplier'])
combined['Unit multiplier'] = combined['Unit multiplier'].fillna(combined['UNIT_MULT'])

In [55]:
combined[['UNIT_MULT', 'Unit multiplier']].isnull().sum()

UNIT_MULT          30
Unit multiplier    30
dtype: int64

In [56]:
combined.isnull().sum()

STRUCTURE                    0
STRUCTURE_ID                 0
STRUCTURE_NAME               0
ACTION                       0
REF_AREA                     0
Reference area               0
MEASURE                      0
Measure                      0
UNIT_MEASURE                 0
Unit of measure              0
SEX                          0
Sex                          0
AGE                          0
Age                          0
LABOUR_FORCE_STATUS          0
Labour force status          0
WORK_PERIOD                  0
Work period                  0
HOURS_TYPE                   0
Hours type                   0
WORKER_STATUS                0
Worker status                0
WORK_TIME_ARNGMNT            0
Working time arrangement     0
AGGREGATION_OPERATION        0
Aggregation operation        0
HOUR_BANDS                   0
Hour bands                   0
JOB_COVERAGE                 0
Job coverage                 0
TIME_PERIOD                  0
Time period                  0
OBS_VALUE                    0
Observation value           30
OBS_STATUS                   0
Observation status           0
UNIT_MULT                   30
Unit multiplier             30
DECIMALS                     0
Decimals                     0
country                      0
dtype: int64

In [57]:
combined['UNIT_MULT'] = combined['UNIT_MULT'].fillna(combined['Unit multiplier'])
combined['Unit multiplier'] = combined['Unit multiplier'].fillna(combined['UNIT_MULT'])

In [58]:
combined[['OBS_VALUE', 'Observation value',
          'OBS_STATUS', 'Observation status',
          'UNIT_MULT', 'Unit multiplier']].isnull().sum()

OBS_VALUE              0
Observation value     30
OBS_STATUS             0
Observation status     0
UNIT_MULT             30
Unit multiplier       30
dtype: int64

In [59]:
# Overwrite duplicates with the master columns
combined['Observation value'] = combined['OBS_VALUE']
combined['Observation status'] = combined['OBS_STATUS']
combined['Unit multiplier'] = combined['UNIT_MULT']

In [60]:
combined[['OBS_VALUE', 'Observation value',
          'OBS_STATUS', 'Observation status',
          'UNIT_MULT', 'Unit multiplier']].isnull().sum()

OBS_VALUE              0
Observation value      0
OBS_STATUS             0
Observation status     0
UNIT_MULT             30
Unit multiplier       30
dtype: int64

In [61]:
combined['UNIT_MULT'] = combined['UNIT_MULT'].fillna(0)
combined['Unit multiplier'] = combined['Unit multiplier'].fillna(0)

In [62]:
combined[['UNIT_MULT', 'Unit multiplier']].isnull().sum()

UNIT_MULT          0
Unit multiplier    0
dtype: int64

In [63]:
combined.isnull().sum()

STRUCTURE                   0
STRUCTURE_ID                0
STRUCTURE_NAME              0
ACTION                      0
REF_AREA                    0
Reference area              0
MEASURE                     0
Measure                     0
UNIT_MEASURE                0
Unit of measure             0
SEX                         0
Sex                         0
AGE                         0
Age                         0
LABOUR_FORCE_STATUS         0
Labour force status         0
WORK_PERIOD                 0
Work period                 0
HOURS_TYPE                  0
Hours type                  0
WORKER_STATUS               0
Worker status               0
WORK_TIME_ARNGMNT           0
Working time arrangement    0
AGGREGATION_OPERATION       0
Aggregation operation       0
HOUR_BANDS                  0
Hour bands                  0
JOB_COVERAGE                0
Job coverage                0
TIME_PERIOD                 0
Time period                 0
OBS_VALUE                   0
Observation value           0
OBS_STATUS                  0
Observation status          0
UNIT_MULT                   0
Unit multiplier             0
DECIMALS                    0
Decimals                    0
country                     0
dtype: int64

In [64]:
combined.shape

(30, 41)